name: python 3.10
channels:
  - conda-forge
dependencies:
  - python=3.10 
  - numpy=1.21.4
  - psutil
  - toolz
  - matplotlib=3.5.0
  - dill
  - pandas=1.3.4
  - partd
  - bokeh
  - dask
  - seaborn=0.9.0
  - scikit-learn=0.20.1
  - nbformat
  - prophet
